version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: $DBNAME
      POSTGRES_USER: $DBUSER
      POSTGRES_PASSWORD: $DBPASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/config/lib.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "$PORT:5432"
